export const DEMO_PRODUCTS = [
  {
    id: "demo-product-123",
    barcode: "123",
    name: "Organic Whole Milk",
    price: 85,
    calories: 150,
    allergens: ["dairy"],
    offer: null,
    image: null,
  },
  {
    id: "demo-product-456",
    barcode: "456",
    name: "Artisan Sourdough",
    price: 65,
    calories: 120,
    allergens: ["gluten"],
    offer: null,
    image: null,
  },
  {
    id: "demo-product-789",
    barcode: "789",
    name: "Mixed Roasted Nuts",
    price: 140,
    calories: 210,
    allergens: ["nuts"],
    offer: { discountPercent: 10 },
    image: null,
  },
  {
    id: "demo-product-012",
    barcode: "012",
    name: "Choco Cookies",
    price: 55,
    calories: 180,
    allergens: ["gluten", "dairy"],
    offer: null,
    image: null,
  },
  {
    id: "demo-product-321",
    barcode: "321",
    name: "Greek Yogurt Cup",
    price: 45,
    calories: 95,
    allergens: ["dairy"],
    offer: null,
    image: null,
  },
  {
    id: "demo-product-654",
    barcode: "654",
    name: "Protein Granola Bar",
    price: 35,
    calories: 130,
    allergens: ["nuts", "soy"],
    offer: { discountPercent: 5 },
    image: null,
  },
] as const;

